sudo: false

language: ruby
bundler_args: --without debug
cache: bundler

rvm:
  - 2.1.5
before_script:
  - cp spec/dummy/config/database-sample.yml spec/dummy/config/database.yml; createdb bulk_data_methods_test
script: bundle exec rake spec
